### ISSUE TITLE
[BUG] schemacrawler 库 ColumnReference.getPrimaryKeyColumn().getFullName() 方法返回带引号的值

### ISSUE THREAD

**Issue by zzwtsy** [pot-mot/jimmer-code-gen-kotlin#7]
jimmer-code-gen 版本：0.0.9
数据库版本：Mysql8.0

当表名为 user 时 `getPrimaryKeyColumn().getFullName()` 返回的值包含引号例如 `xxx."user".xxx`
似乎是因为 user 为 MySQL 的保留字

出现问题的位置
https://github.com/pot-mot/jimmer-code-gen-kotlin/blob/f604e56428fb9af89a483cb22d7a6ec473a1c82b/src/main/kotlin/top/potmot/core/database/meta/ColumnReferenceMeta.kt#L43

**Comment by pot-mot** [comment]
因为`"user"`、`user`都是合法的mysql表名，所以无法通过强制去除两侧符号处理。
目前我不再使用`fullName`而是直接基于`primaryKeyColumn.key().toString()`进行字符串截取操作。

**Comment by pot-mot** [comment]
请尝试 [0.1.0-Preview](https://github.com/pot-mot/jimmer-code-gen-kotlin/releases/tag/0.1.0-Preview)
